name: "mdt_edited"

arch: 
  _target_: model.MDT_Edited.MDT_Edited
  cfg:
    dim: 48
    num_blocks: [6, 6, 12, 8]
    num_refinement_blocks: 4
    ffn_expansion_factor: 3
    img_size: ${dataset.patch_size}
