name: "mdt_dpt"

arch:
  _target_: model.MDT_DPT.MDT_DPT
  cfg:
    # ViT Backbone
    num_vit_layers: 12
    embed_dim: 768
    num_heads: 12
    
    # Resolution & Patching
    patch_size_vit: 16
    
    # DPT Config
    reassemble_layers: [2, 5, 8, 11]
    decoder_channels: 256
    
    # Depth Integration
    use_depth: true
    depth_model_repo: "depth-anything/Depth-Anything-V2-Large-hf"
    
    dim: 48 
    num_blocks: [6, 6, 12, 8]
    num_refinement_blocks: 4
    ffn_expansion_factor: 3
    img_size: ${dataset.patch_size}
