logger_name: "${model.name}"
logger_filename: "log.out"
log_dir: "${hydra:runtime.output_dir}/logs"
logger_level: 0

tensorboard_dir: "${hydra:runtime.cwd}/tensorboard/${model.name}/${now:%Y-%m-%d_%H-%M-%S}"
dir: outputs//
