src_root: ${hydra:runtime.cwd}/data/GoPro/raw
dst_root: ${hydra:runtime.cwd}/data/GoPro/processed
img_size: [128, 128]
num_workers: 8

augmentations:
  _target_: albumentations.Compose
  transforms:
    # 1. Padding
    - _target_: albumentations.PadIfNeeded
      min_height: ${dataset.patch_size[0]}
      min_width: ${dataset.patch_size[1]}
      border_mode: 4  # 4 is cv2.BORDER_REFLECT_101
      p: 1.0

    # 2. Random Crop
    - _target_: albumentations.RandomCrop
      height: ${dataset.patch_size[0]}
      width: ${dataset.patch_size[1]}
      p: 1.0
    
    # 3. Flip
    - _target_: albumentations.HorizontalFlip
      p: 0.5
    
    # 4. Color/Intensity Augmentations
    - _target_: albumentations.RandomGamma
      gamma_limit: [80, 120]
      p: 0.5
    - _target_: albumentations.HueSaturationValue
      hue_shift_limit: 0
      sat_shift_limit: 30
      val_shift_limit: 0
      p: 0.5

  additional_targets:
    sharp: image
