src_root: ${hydra:runtime.cwd}/data/GoPro/raw
dst_root: ${hydra:runtime.cwd}/data/GoPro/processed
img_size: [360, 640]
num_workers: 3

augmentations:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: ${dataset.img_size[0]}
      width: ${dataset.img_size[1]}
      p: 1.0
    
    - _target_: albumentations.HorizontalFlip
      p: 0.5
    
    - _target_: albumentations.RandomGamma
      gamma_limit: [80, 120]
      p: 0.5

    - _target_: albumentations.HueSaturationValue
      hue_shift_limit: 0
      sat_shift_limit: 30
      val_shift_limit: 0
      p: 0.5

  additional_targets:
    sharp: image
