src_root: ${hydra:runtime.cwd}/data/GoPro/raw
dst_root: ${hydra:runtime.cwd}/data/GoPro/processed
patch_size: 128
num_workers: 4

augmentations:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.RandomCrop
      height: ${dataset.patch_size}
      width: ${dataset.patch_size}
      p: 1.0
    
    - _target_: albumentations.HorizontalFlip
      p: 0.5
    
    - _target_: albumentations.RandomGamma
      gamma_limit: [80, 120]
      p: 0.5

    - _target_: albumentations.HueSaturationValue
      hue_shift_limit: 0
      sat_shift_limit: 30
      val_shift_limit: 0
      p: 0.5

  additional_targets:
    sharp: image
