defaults:
  - _self_
  - dataset: gopro_lmdb
  - model: mdphysics
  - metrics: default
  - logger: default
  - train: stage3

device: "cuda:0"
seed: 42

hydra:
  run:
    dir: outputs/${model.name}/stage_${train.stage}/${now:%Y-%m-%d_%H-%M-%S}

