defaults:
  - _self_
  - dataset: gopro_lmdb
  - model: mdt
  - metrics: default
  - logger: default
  - train: default

device: "cuda:0"
seed: 42

hydra:
  run:
    dir: outputs/${model.name}/${now:%Y-%m-%d_%H-%M-%S}

