hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false

src_root: ../datasets/GOPRO_Large
dst_root: data/GoPro/raw

val_split: 0.025
seed: 42

splits:
  - train
  - test

modes:
  - blur
  - sharp

ignore:
  - blur_gamma

download: false
copy: true

