defaults:
  - _self_
  - dataset: gopro_test
  - model: mdt_edited
  - metrics: test
  - logger: default
  - train: test

device: "cuda:0"
seed: 42

hydra:
  run:
    dir: outputs/${model.name}/test/${now:%Y-%m-%d_%H-%M-%S}

