stage: 2

lr: 1e-4
weight_decay: 1e-3
epochs: 100
batch_size: 16
batch_size_val: 8

criterion:
  _target_: utils.losses.LossContainer
  cfg:
    sharp_image:
      weight: 1.0
      loss:
        _target_: utils.losses.CharbonnierLoss
        reduction: mean

optimizer:
  _target_: torch.optim.AdamW
  lr: ${train.lr}
  weight_decay: ${train.weight_decay}

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.epochs}

freeze:
  - reassemble_blocks
  - depth_fusion_blocks
  - motion_fusion_blocks
  - depth_head
  - motion_head

checkpoint:
  dir: "${hydra:runtime.output_dir}/checkpoints"
  patience: 10
  min_delta: 1e-4
  monitor: ssim
  mode: max

last_checkpoint: ""
